---
driver:
  name: docker
  use_sudo: false

platforms:
  - name: centos-6.8

suites:
  - name: hygieia-liatrio
    encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
    run_list:
      - recipe[yum-epel::default]
      - recipe[jenkins-liatrio::default]
      - recipe[jenkins-liatrio::plugin_maven]
    attributes:
      java:
        jdk_version: "8"
