---
driver:
  name: docker
  use_sudo: false
  require_chef_omnibus: 12.16.42

  # XXX consider adding a docker container with chef-client already installed
  # require_chef_omnibus: false
  # provision_command: curl -L https://www.opscode.com/chef/install.sh | bash

platforms:
  - name: centos-6.8

suites:
  - name: jenkins-liatrio
    run_list:
      - recipe[yum-epel::default]
      - recipe[jenkins-as-code::default]
      - recipe[jenkins-as-code::create_jobs]
    attributes:
      java:
        jdk_version: "8"
